# THIS FILE IS USED ONLY DURING DEVELOPMENT AND DEBUGGING!
# THE VERSION IN THIS FILE IS NOT THE REAL VERSION!
# THE RELEVANT VERSION NUMBER IS MAINTAINED IN pyproject.toml AND default.nix
VERSION = "0.0.0.0"
