# possible system properties (no magic strings)
STAR_CLASS = {}
STAR_CLASS.A="A"
STAR_CLASS.B="B"
STAR_CLASS.O="O"
STAR_CLASS.F="F"
STAR_CLASS.G="G"
STAR_CLASS.K="K"
STAR_CLASS.M="M"
STAR_CLASS.S="S"
STAR_CLASS.D="D"
STAR_CLASS.BH="black hole"

STAR_LUMINOSITY = {}
STAR_LUMINOSITY.I="I"
STAR_LUMINOSITY.II="II"
STAR_LUMINOSITY.III="III"
STAR_LUMINOSITY.IV="IV"
STAR_LUMINOSITY.V="V"
STAR_LUMINOSITY.VI="VI"



